### ISSUE TITLE
Pasting URLs without http* prefix cause app crash

### ISSUE THREAD

**Issue by Albioza** [teneusz/ZippyShareDownloader#1]
**Problem:** Any web URL without http or https prefix pasted into "Add links" window cause application crash after pushing "add" button.
**Possible solution:** Skip these links or set their status into "Incorect service link" or try to fix them by attempting to get HTTP/200 code by assigning correct prefix to link.

**Comment by teneusz** [comment]
If link is without prefix "http://" or "https://" then prefix "http://" is added
