### ISSUE TITLE
Implement download check system

### ISSUE THREAD

**Issue by Albioza** [teneusz/ZippyShareDownloader#3]
It is annoying that you download 50 parts of one file and you realize that few of them were not downloaded properly.
Those wrong files are usually small (something like 1-200 kB), they have proper file names and extension but it's just .html file
How to fix it ?
My solution should look like this: Start download -> finish download -> if downloaded file size matches file size declared on download page then 'accept' download if not attempt to re-download or add icon (something like a refresh icon that you can see in your browser) next to progress bar to download file again.

**Comment by teneusz** [comment]
One of the possible solutions is already committed.
